targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: lib/core/data/api
          output_folder: lib/core/data/api/.generated
          separate_models: true
