name: enpal_assignment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Code Generation Annotations
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Internationalization
  intl: ^0.20.1

  # OpenAPI Generator
  openapi_generator_annotations: ^6.1.0
  chopper: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  openapi_generator: ^6.1.0
  chopper_generator: ^8.0.3
  swagger_dart_code_generator: ^3.0.1

flutter:
  uses-material-design: true
